name: 'Remove Tag'
description: 'Removes a tag and respective releases on the GitHub repo (e.g. "latest")'
inputs:
  tag:  # id of input
    description: 'The name of the tag with corresponding release to delete'
    required: true
    default: 'latest'
  GITHUB_TOKEN:
    description: 'GitHub Auth Token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
